version: "3.9"

services:
  app:
    build: .
    container_name: ihf-app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env.docker
    depends_on:
      - mongo
      - postgres
    networks:
      - backend

  mongo:
    image: mongo:8.0.12
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ./.env.docker
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env.docker
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  mongo_data:
  postgres_data:

networks:
  backend:
    driver: bridge
